"use client";

import Image from "next/image";
import { CalendarDays, MapPin, Plus, Users, X } from "lucide-react";
import { useEffect, useState } from "react";
import { PageHeader } from "@/components/ui/page-header";
import { trips as fallbackTrips } from "@/data/mock-data";
import { createClient, isSupabaseConfigured } from "@/lib/supabase/client";

interface TripView { id: string; name: string; location: string; date: string; price: number; seats: number; image: string; }

export default function TripsPage() {
  const [trips, setTrips] = useState<TripView[]>(fallbackTrips); const [open, setOpen] = useState(false); const [requested, setRequested] = useState<string[]>([]);
  useEffect(() => { if (!isSupabaseConfigured()) return; const supabase = createClient(); supabase.from("trips").select("id,name,location,starts_at,price_myr,seats").eq("status", "open").order("starts_at").then(({ data }) => { if (data?.length) setTrips([...data.map((row, index) => ({ id: row.id, name: row.name, location: row.location, date: new Date(row.starts_at).toLocaleDateString("en-MY", { day: "numeric", month: "short", year: "numeric" }), price: Number(row.price_myr), seats: row.seats, image: fallbackTrips[index % fallbackTrips.length].image })), ...fallbackTrips]); }); }, []);
  async function createTrip(formData: FormData) { if (!isSupabaseConfigured()) return; const supabase = createClient(); const { data } = await supabase.auth.getUser(); if (!data.user) return void window.location.assign("/auth"); const result = await supabase.from("trips").insert({ organiser_id: data.user.id, name: String(formData.get("name")), location: String(formData.get("location")), starts_at: new Date(String(formData.get("date"))).toISOString(), price_myr: Number(formData.get("price")), seats: Number(formData.get("seats")) }).select("id").single(); if (result.error) throw result.error; setOpen(false); window.location.reload(); }
  async function request(id: string) { if (!isSupabaseConfigured() || id.startsWith("trip-")) return; const supabase = createClient(); const { data } = await supabase.auth.getUser(); if (!data.user) return void window.location.assign("/auth"); const result = await supabase.from("trip_members").upsert({ trip_id: id, user_id: data.user.id }); if (!result.error) setRequested((value) => [...value, id]); }
  return <div className="page-container standard-page"><PageHeader eyebrow="Plan together" title="Fishing trips" description="Discover departures organised by the Malaysian angling community." action={<button className="primary-button" onClick={() => setOpen(true)}><Plus />Create trip</button>} /><div className="listing-grid">{trips.map((trip) => <article className="listing-card surface" key={trip.id}><div className="listing-image"><Image src={trip.image} fill sizes="(max-width: 700px) 100vw, 380px" alt={trip.name}/><span>{trip.seats} seats</span></div><div className="listing-copy"><p className="eyebrow"><MapPin />{trip.location}</p><h2>{trip.name}</h2><div className="listing-meta"><span><CalendarDays />{trip.date}</span><span><Users />Community trip</span></div><div className="listing-footer"><strong>RM{trip.price}<small>/person</small></strong><button className="secondary-button" disabled={requested.includes(trip.id)} onClick={() => request(trip.id)}>{requested.includes(trip.id) ? "Requested" : "Request seat"}</button></div></div></article>)}</div>
    {open && <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="trip-title"><form action={createTrip}><div className="modal-head"><div><p className="eyebrow">Community trip</p><h2 id="trip-title">Create fishing trip</h2></div><button className="icon-button" type="button" onClick={() => setOpen(false)} aria-label="Close"><X /></button></div><div className="form-grid"><label className="wide">Trip name<input required name="name" /></label><label>Location<input required name="location" /></label><label>Date<input required name="date" type="datetime-local" /></label><label>Price per person (RM)<input required name="price" type="number" min="0" /></label><label>Available seats<input required name="seats" type="number" min="1" /></label></div><button className="primary-button wide-button">Publish trip</button></form></section></div>}
  </div>;
}
